### ISSUE TITLE
Sage 10.0.0 release checklist

### ISSUE THREAD

**Issue by retlehs** [roots/sage#2357]
* [x] Sage 10 initial documentation 
  * [ ] [Update compiling assets docs](https://github.com/roots/docs/issues/319)
* [x] Acorn initial documentation
  * [ ] [Finish required docs](https://github.com/roots/docs/issues/315)
* [x] Tag an Acorn release and no longer target `dev-master`
* [x] Update Acorn to Laravel 8 (@QWp6t @Log1x)
* [x] Update README
  * [x] Mention Acorn (#2827)
  * [x] Remove Laravel Mix and add stuff about Bud (#2850)
  * [x] Update scripts references (`yarn start` is now `yarn dev`; `yarn build` builds for production) (#2850)
* [x] Finish blog post/announcement 
* [x] Release 10.0.0-beta.3
* [ ] Release 10.0.0-beta.4

Sage 10 milestone on the docs repo: https://github.com/roots/docs/milestones/Sage%2010.0.0

**Release date: TBD**

Upcoming milestones: https://github.com/roots/sage/milestones

**Comment by catgofire** [comment]
@retlehs This commit eb6f41fcf00824422f38386f88cee53d757b0a87 from https://github.com/roots/sage/pull/2429 checks the first box

**Comment by sparkbold** [comment]
@retlehs Great to hear about the update!! Since Sage 10 would be ready to release soon, which branch should I use for development? master or 10.0.0-dev? or it doesn't matter. We plan to upgrade our site from sage 9. If there is a documentation would be great (I am gladly to support. We bought all your books but they are quite outdated.)

**Comment by QWp6t** [comment]
@sparkbold Currently the most significant blocker for Sage 10 is probably #2504

It is almost certain that we'll be abandoning Mix for Bud. (Also, I just want to give a massive thank you to @kellymears for developing bud. It's a fantastic project, and we're all very excited to see it land in Sage.)

We're also working on updating Acorn to Laravel 8 components, and that might introduce some breaking changes (minimal impact, but breaking nonetheless) so we could see Acorn v2 in Sage 10 as well.

**Comment by eduardoarandah** [comment]
> @sparkbold Currently the most significant blocker for Sage 10 is probably #2504
> 
> It is almost certain that we'll be abandoning Mix for Bud. (Also, I just want to give a massive thank you to @kellymears for developing bud. It's a fantastic project, and we're all very excited to see it land in Sage.)
> 
> We're also working on updating Acorn to Laravel 8 components, and that might introduce some breaking changes (minimal impact, but breaking nonetheless) so we could see Acorn v2 in Sage 10 as well.

I'm confused about this comment about changing mix for roots/bud. 

I saw bud repo and it says it's a cli tool, and laravel mix is a webpack simplifier, isn't it?

Also: seems like a change in laravel mix is a breaking change

I must be missing something, searched in discourse but didn't find references to "roots/bud"

**Comment by dsturm** [comment]
Hey @eduardoarandah,

`roots/bud` was the name for the CLI tool but [will be renamed to `roots/clover`](https://github.com/roots/bud/tree/v2.0.0#overview) in version 2.0. Though `roots/bud` will (likely) be the replacement for Laravel Mix.

**Comment by simboonlong** [comment]
curious if there is a tentative date on v10 release?

**Comment by alexbohariuc** [comment]
> curious if there is a tentative date on v10 release?

Also interested - I'm actually using Sage 10 for a personal project in production, and it's quite stable.

**Comment by Sergyus** [comment]
How to fix that? Target class [assets] does not exist.

**Comment by mrkaluzny** [comment]
Any idea for the release date? 2 years is a lot of time to keep us waiting 😂

**Comment by retlehs** [comment]
this issue is being used internally by the roots team for us to track our steps to launch

please use https://discourse.roots.io/ for questions, or join us on the roots slack by becoming a patron or github sponsor
